package com.ykh.pojo;

import java.util.Date;

/**
 * Cdrconferencemsg generated by MyEclipse Persistence Tools
 */

public class Cdrconferencemsg implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer tempconferenceid;
	private Integer actiontypeid;
	private Date timestamp;

	// Constructors

	/** default constructor */
	public Cdrconferencemsg() {
	}

	/** minimal constructor */
	public Cdrconferencemsg(Integer id, Integer tempconferenceid) {
		this.id = id;
		this.tempconferenceid = tempconferenceid;
	}

	/** full constructor */
	public Cdrconferencemsg(Integer id, Integer tempconferenceid,
			Integer actiontypeid, Date timestamp) {
		this.id = id;
		this.tempconferenceid = tempconferenceid;
		this.actiontypeid = actiontypeid;
		this.timestamp = timestamp;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTempconferenceid() {
		return this.tempconferenceid;
	}

	public void setTempconferenceid(Integer tempconferenceid) {
		this.tempconferenceid = tempconferenceid;
	}

	public Integer getActiontypeid() {
		return this.actiontypeid;
	}

	public void setActiontypeid(Integer actiontypeid) {
		this.actiontypeid = actiontypeid;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

}