package com.ykh.pojo;

import java.util.Date;

/**
 * Cdruserinfo generated by MyEclipse Persistence Tools
 */

public class Cdruserinfo implements java.io.Serializable {

	// Fields

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer tempuserid;
	private Integer tempconferenceid;
	private Date timestamp;
	private Integer actiontypeid;
	private String ipaddr;
	private String username;
	private Integer clienttype;
	private Integer domain;
	
	private String role;
	private String serveraddr;
	private String proxyaddr;
	private Integer pin;
	private Integer msgtimestamp;
	
	// Constructors

	/** default constructor */
	public Cdruserinfo() {
	}

	/** full constructor */
	public Cdruserinfo(Integer tempuserid, Integer tempconferenceid, Date timestamp, Integer actiontypeid, String ipaddr, String username,Integer clienttype,Integer domain,
			String role,String serveraddr,String proxyaddr,Integer pin,Integer msgtimestamp) {
		this.tempuserid = tempuserid;
		this.tempconferenceid = tempconferenceid;
		this.timestamp = timestamp;
		this.actiontypeid = actiontypeid;
		this.ipaddr = ipaddr;
		this.username = username;
		this.clienttype = clienttype;
		this.domain = domain;
		this.role = role;
		this.serveraddr = serveraddr;
		this.proxyaddr = proxyaddr;
		this.pin = pin;
		this.msgtimestamp = msgtimestamp;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTempuserid() {
		return this.tempuserid;
	}

	public void setTempuserid(Integer tempuserid) {
		this.tempuserid = tempuserid;
	}

	/**
	 * tempconferenceid
	 * 
	 * @return the tempconferenceid
	 */

	public Integer getTempconferenceid() {
		return tempconferenceid;
	}

	/**
	 * tempconferenceid
	 * 
	 * @param tempconferenceid
	 *            the tempconferenceid to set
	 */

	public void setTempconferenceid(Integer tempconferenceid) {
		this.tempconferenceid = tempconferenceid;
	}

	
	public Date getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public Integer getActiontypeid() {
		return actiontypeid;
	}

	public void setActiontypeid(Integer actiontypeid) {
		this.actiontypeid = actiontypeid;
	}

	public String getIpaddr() {
		return this.ipaddr;
	}

	public void setIpaddr(String ipaddr) {
		this.ipaddr = ipaddr;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getClienttype() {
		return clienttype;
	}

	public void setClienttype(Integer clienttype) {
		this.clienttype = clienttype;
	}

	public Integer getDomain() {
		return domain;
	}

	public void setDomain(Integer domain) {
		this.domain = domain;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getServeraddr() {
		return serveraddr;
	}

	public void setServeraddr(String serveraddr) {
		this.serveraddr = serveraddr;
	}

	public String getProxyaddr() {
		return proxyaddr;
	}

	public void setProxyaddr(String proxyaddr) {
		this.proxyaddr = proxyaddr;
	}

	public Integer getPin() {
		return pin;
	}

	public void setPin(Integer pin) {
		this.pin = pin;
	}

	public Integer getMsgtimestamp() {
		return msgtimestamp;
	}

	public void setMsgtimestamp(Integer msgtimestamp) {
		this.msgtimestamp = msgtimestamp;
	}

	

}