//package com.ykh.pojo;
//
//import com.sun.xml.bind.CycleRecoverable;
//
//import javax.xml.bind.annotation.XmlRootElement;
//
///**
// * Conferenceprivilege generated by MyEclipse Persistence Tools
// */
//@XmlRootElement
//public class Conferenceprivilege implements java.io.Serializable, CycleRecoverable {
//
//	// Fields
//
//	private static final long serialVersionUID = 1L;
//	private Integer privilegeid;
////	private Conferenceservice conferenceservice;
////	private Conferencerole conferencerole;
//	private String privilegename;
//	private Integer privilegevalue;
//	private Integer roleid;
//	private Integer conferenceserviceid;
//
//	// Constructors
//
//	/** default constructor */
//	public Conferenceprivilege() {
//	}
//
//	/** full constructor */
//	public Conferenceprivilege(String privilegename,Integer privilegevalue) {
////		this.conferenceservice = conferenceservice;
////		this.conferencerole = conferencerole;
//		this.privilegename = privilegename;
//		this.privilegevalue = privilegevalue;
//	}
//
//	@Override
//	public Object onCycleDetected(Context context) {
//		Conferenceprivilege tempConfprivilege = new Conferenceprivilege();
//		tempConfprivilege.setPrivilegeid(privilegeid);
//		return tempConfprivilege;
//	}
//
//	// Property accessors
//	public int hashCode() {
//
//		int result = 179;
//		result = 37 * result + (privilegeid == null ? System.identityHashCode(this) : privilegeid.hashCode());
//		return result;
//	}
//
//	public Integer getPrivilegeid() {
//		return this.privilegeid;
//	}
//
//	public void setPrivilegeid(Integer privilegeid) {
//		this.privilegeid = privilegeid;
//	}
//
////	@XmlElement(name="conferenceservice")
////	public Conferenceservice getConferenceservice() {
////		return this.conferenceservice;
////	}
////
////	public void setConferenceservice(Conferenceservice conferenceservice) {
////		this.conferenceservice = conferenceservice;
////	}
//
////	@XmlElement(name="conferencerole")
////	public Conferencerole getConferencerole() {
////		return this.conferencerole;
////	}
////
////	public void setConferencerole(Conferencerole conferencerole) {
////		this.conferencerole = conferencerole;
////	}
//
//	public String getPrivilegename() {
//		return this.privilegename;
//	}
//
//	public void setPrivilegename(String privilegename) {
//		this.privilegename = privilegename;
//	}
//
//	public Integer getPrivilegevalue() {
//		return privilegevalue;
//	}
//
//	public void setPrivilegevalue(Integer privilegevalue) {
//		this.privilegevalue = privilegevalue;
//	}
//
//	public Integer getRoleid() {
//		return roleid;
//	}
//
//	public void setRoleid(Integer roleid) {
//		this.roleid = roleid;
//	}
//
//	public Integer getConferenceserviceid() {
//		return conferenceserviceid;
//	}
//
//	public void setConferenceserviceid(Integer conferenceserviceid) {
//		this.conferenceserviceid = conferenceserviceid;
//	}
//
//}