package com.ykh.pojo;

import com.sun.xml.bind.CycleRecoverable;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicelib generated by MyEclipse Persistence Tools
 */
@XmlRootElement
public class Servicelib implements java.io.Serializable, CycleRecoverable {

	// Fields

	private static final long serialVersionUID = 1L;
	private Integer servicelibid;
	private Servicelibtype servicelibtype;
	private Integer servicelibcode;
	private String servicelibname;
	private Date addtime;
	private String servicelibstatu;
	private String servicelibdesc;
	private String createby;
	private Set<Servicelibvalue> servicelibvalues = new HashSet<Servicelibvalue>(0);
	private Set<Conferenceservice> conferenceservices = new HashSet<Conferenceservice>(0);

	// Constructors

	/** default constructor */
	public Servicelib() {
	}

	/** full constructor */
	public Servicelib(Servicelibtype servicelibtype, Integer servicelibcode, String servicelibname, Date addtime, String servicelibstatu,
			String servicelibdesc, String createby, Set<Servicelibvalue> servicelibvalues, Set<Conferenceservice> conferenceservices) {
		this.servicelibtype = servicelibtype;
		this.servicelibcode = servicelibcode;
		this.servicelibname = servicelibname;
		this.addtime = addtime;
		this.servicelibstatu = servicelibstatu;
		this.servicelibdesc = servicelibdesc;
		this.createby = createby;
		this.servicelibvalues = servicelibvalues;
		this.conferenceservices = conferenceservices;
	}
	
	@Override
	public Object onCycleDetected(Context context) {
		Servicelib tempServicelib = new Servicelib();
		tempServicelib.setServicelibid(servicelibid);
		return tempServicelib;
	}


	// Property accessors
	public int hashCode() {

		int result = 179;
		result = 37 * result + (servicelibid == null ? System.identityHashCode(this) : servicelibid.hashCode());
		return result;
	}
	public Integer getServicelibid() {
		return this.servicelibid;
	}

	public void setServicelibid(Integer servicelibid) {
		this.servicelibid = servicelibid;
	}

	@XmlElement(name="servicelibtype")
	public Servicelibtype getServicelibtype() {
		return this.servicelibtype;
	}

	public void setServicelibtype(Servicelibtype servicelibtype) {
		this.servicelibtype = servicelibtype;
	}

	public Integer getServicelibcode() {
		return this.servicelibcode;
	}

	public void setServicelibcode(Integer servicelibcode) {
		this.servicelibcode = servicelibcode;
	}

	public String getServicelibname() {
		return this.servicelibname;
	}

	public void setServicelibname(String servicelibname) {
		this.servicelibname = servicelibname;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public String getServicelibstatu() {
		return this.servicelibstatu;
	}

	public void setServicelibstatu(String servicelibstatu) {
		this.servicelibstatu = servicelibstatu;
	}

	public String getServicelibdesc() {
		return this.servicelibdesc;
	}

	public void setServicelibdesc(String servicelibdesc) {
		this.servicelibdesc = servicelibdesc;
	}

	public String getCreateby() {
		return this.createby;
	}

	public void setCreateby(String createby) {
		this.createby = createby;
	}

	@XmlElement(name="servicelibvalues")
	public Set<Servicelibvalue> getServicelibvalues() {
		return this.servicelibvalues;
	}

	public void setServicelibvalues(Set<Servicelibvalue> servicelibvalues) {
		this.servicelibvalues = servicelibvalues;
	}

	@XmlElement(name="conferenceservices")
	public Set<Conferenceservice> getConferenceservices() {
		return this.conferenceservices;
	}

	public void setConferenceservices(Set<Conferenceservice> conferenceservices) {
		this.conferenceservices = conferenceservices;
	}
}