//package com.ykh.pojo;
//
//import com.sun.xml.bind.CycleRecoverable;
//
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlRootElement;
//import java.util.HashSet;
//import java.util.Set;
//
///**
// * Servicelibvalue generated by MyEclipse Persistence Tools
// */
//@XmlRootElement
//public class Servicelibvalue implements java.io.Serializable, CycleRecoverable {
//
//	// Fields
//
//	private static final long serialVersionUID = 1L;
//	private Integer servicelibvalueid;
//	private Servicelib servicelib;
//	private String servicevalue;
//	private Integer servicelibvaluecode;
//	private Set<Conferenceservicevalue> conferenceservicevalues = new HashSet<Conferenceservicevalue>(0);
//
//	// Constructors
//
//	/** default constructor */
//	public Servicelibvalue() {
//	}
//
//	/** full constructor */
//	public Servicelibvalue(Servicelib servicelib, String servicevalue, Integer servicelibvaluecode, Set<Conferenceservicevalue> conferenceservicevalues) {
//		this.servicelib = servicelib;
//		this.servicevalue = servicevalue;
//		this.servicelibvaluecode = servicelibvaluecode;
//		this.conferenceservicevalues = conferenceservicevalues;
//	}
//
//	@Override
//	public Object onCycleDetected(Context context) {
//		Servicelibvalue tempServicelibvalue = new Servicelibvalue();
//		tempServicelibvalue.setServicelibvalueid(servicelibvalueid);
//		return tempServicelibvalue;
//	}
//
//	// Property accessors
//	public int hashCode() {
//
//		int result = 179;
//		result = 37 * result + (servicelibvalueid == null ? System.identityHashCode(this) : servicelibvalueid.hashCode());
//		return result;
//	}
//	public Integer getServicelibvalueid() {
//		return this.servicelibvalueid;
//	}
//
//	public void setServicelibvalueid(Integer servicelibvalueid) {
//		this.servicelibvalueid = servicelibvalueid;
//	}
//
//	@XmlElement(name="servicelib")
//	public Servicelib getServicelib() {
//		return this.servicelib;
//	}
//
//	public void setServicelib(Servicelib servicelib) {
//		this.servicelib = servicelib;
//	}
//
//	public String getServicevalue() {
//		return this.servicevalue;
//	}
//
//	public void setServicevalue(String servicevalue) {
//		this.servicevalue = servicevalue;
//	}
//
//	public Integer getServicelibvaluecode() {
//		return this.servicelibvaluecode;
//	}
//
//	public void setServicelibvaluecode(Integer servicelibvaluecode) {
//		this.servicelibvaluecode = servicelibvaluecode;
//	}
//
//	@XmlElement(name="conferenceservicevalues")
//	public Set<Conferenceservicevalue> getConferenceservicevalues() {
//		return this.conferenceservicevalues;
//	}
//
//	public void setConferenceservicevalues(Set<Conferenceservicevalue> conferenceservicevalues) {
//		this.conferenceservicevalues = conferenceservicevalues;
//	}
//}