package com.ykh.pojo;

/**
 * Tempconfid generated by MyEclipse Persistence Tools
 */

public class Tempconfid implements java.io.Serializable {

	// Fields

	/**
	 * serialVersionUID:TODO�
	 *
	 * @since Ver 1.0
	 */
	
	private static final long serialVersionUID = 1L;
	private Integer cid;

	// Constructors

	/** default constructor */
	public Tempconfid() {
	}

	// Property accessors

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

}