package com.ykh.pojo;

import java.util.Date;

/**
 * Tempconfid generated by MyEclipse Persistence Tools
 */

public class Tempuser implements java.io.Serializable {

	// Fields
	
	private static final long serialVersionUID = 1L;
	private Integer uid;
	private Integer tempconfid;
	private Integer tempuserid;
	private Long userID;
	private Date createtime; 

	// Constructors

	/** default constructor */
	public Tempuser() {
	}

	public Integer getUid() {
		return uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Integer getTempconfid() {
		return tempconfid;
	}

	public void setTempconfid(Integer tempconfid) {
		this.tempconfid = tempconfid;
	}

	public Integer getTempuserid() {
		return tempuserid;
	}

	public void setTempuserid(Integer tempuserid) {
		this.tempuserid = tempuserid;
	}

	public Long getUserID() {
		return userID;
	}

	public void setUserID(Long userID) {
		this.userID = userID;
	}

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
	
}