package com.ykh.services.conference;


import javax.xml.bind.annotation.XmlRootElement;


/**
 * Conferenceuservalue generated by MyEclipse Persistence Tools
 */
@XmlRootElement
public class Conferenceuservalue implements java.io.Serializable {

	// Fields

	private static final long serialVersionUID = 1L;
	private Integer conferenceuservalueid;
//	private Conferenceservice conferenceservice;
//	private Conference conference;
	private Integer value;

	private Integer conferenceserviceid;
	// Constructors

	/** default constructor */
	public Conferenceuservalue() {
	}

//	/** full constructor */
//	public Conferenceuservalue(Conferenceservice conferenceservice, Conference conference, Integer value) {
////		this.conferenceservice = conferenceservice;
//		this.conference = conference;
//		this.value = value;
//	}
//	
//	@Override
//	public Object onCycleDetected(Context arg0) {
//		Conferenceuservalue tempConfuservalue = new Conferenceuservalue();
//		tempConfuservalue.setConferenceuservalueid(conferenceuservalueid);
//		return tempConfuservalue;
//	}

	// Property accessors
	public int hashCode() {

		int result = 179;
		result = 37 * result + (conferenceuservalueid == null ? System.identityHashCode(this) : conferenceuservalueid.hashCode());
		return result;
	}
	public Integer getConferenceuservalueid() {
		return this.conferenceuservalueid;
	}

	public void setConferenceuservalueid(Integer conferenceuservalueid) {
		this.conferenceuservalueid = conferenceuservalueid;
	}

//	@XmlElement(name="conferenceservice")
//	public Conferenceservice getConferenceservice() {
//		return this.conferenceservice;
//	}
//
//	public void setConferenceservice(Conferenceservice conferenceservice) {
//		this.conferenceservice = conferenceservice;
//	}

//	@XmlElement(name="conference")
//	public Conference getConference() {
//		return this.conference;
//	}
//
//	public void setConference(Conference conference) {
//		this.conference = conference;
//	}

	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

	public Integer getConferenceserviceid() {
		return conferenceserviceid;
	}

	public void setConferenceserviceid(Integer conferenceserviceid) {
		this.conferenceserviceid = conferenceserviceid;
	}
	
}